[display]
disable_image_preview = false
show_avatars = true
show_images = true
media_playback = true
image_preview_quality = "balanced"
attachment_viewer_quality = "original"
image_protocol = "auto"
show_custom_emoji = true
circular_avatars = true

[composer]
emojis_as_links = false

[credentials]
store = "auto"

[notifications]
desktop_notifications = true
notification_icon = "/usr/share/icons/apps/concord/discord-v2.svg"

[voice]
self_mute = false
self_deaf = false
allow_microphone_transmit = false
microphone_sensitivity = -30
microphone_volume = 100
voice_output_volume = 100
