-- #######################################################################################
-- Hyprland Config File
-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
-- #######################################################################################

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--#############
--## CONFIG ###
--#############

require("config.monitors")
require("config.environment-variables")
require("config.autostart")
require("config.style")
require("config.input")
require("config.keybinds")
require("config.window-rules")
require("config.system")
