[pyprland]
plugins = [
  "expose",
  "scratchpads",
  "magnify",
  "shortcuts_menu",
	"fetch_client_menu"
]

[expose]
include_special = false

[scratchpads.stb]
animation = "fromBottom"
command = "kitty --class kitty-stb sstb"
class = "kitty-stb"
lazy = true
size = "75% 45%"

[scratchpads.calc]
animation = "fromBottom"
command = "kitty --class kitty-calc kalc"
class = "kitty-calc"
lazy = true
size = "50% 25%"

[scratchpads.notes]
animation = "fromTop"
command = "cd ~/Documents/Notes/Tanner/ && kitty --class kitty-notes nvim"
class = "kitty-notes"
lazy = true
size = "75% 80%"

[scratchpads.stb-logs]
animation = "fromTop"
command = "kitty --class kitty-stb-logs stbLog"
class = "kitty-stb-logs"
lazy = true
size = "75% 40%"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.volume]
animation = "fromLeft"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = false
size = "40% 90%"
unfocus = "hide"

[scratchpads.music]
animation = "fromRight"
command = "cider"
class = "cider"
lazy = false
size = "60% 90%"

[shortcuts_menu]
engine = "fuzzel"
parameters = "--dmenu"
[shortcuts_menu.entries]
"Connect To Server" = [
    {name="server", options=["dbk-dev", "app-deploy.dayback.me", "app-us-west-deploy.dayback.me", "app-au-deploy.dayback.me", "staging-deploy.dayback.me", "beta-deploy.dayback.me", "dbk-recover", "legacy", "services", "zebes", "dp-dev-admin", "dp-server-staging", "dp-server-beta", "dp-server"]},
	"kitty -e ssh [server]"
]
"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --format [format] | wl-copy" # sleep to let the menu close before the picker opens
]
